### ISSUE TITLE
tests fail if you don't have yarn

### ISSUE THREAD

**Issue by filmaj** [adobe/stock-api-libjs#1]
I only have `npm`. Is that bad? Is `yarn` required to run this project?

Perhaps we can either a) update the `test` script in `package.json` to call `npm run lint` instead of `yarn run lint` or b) make explicit in a new requirements section in the README that `yarn` is required. Or maybe we can use `package.json`'s `engines` field for this, too?

**Comment by slaanesh** [comment]
yarn is required and #2 adds this specification to the README so I think it should enough. Or you suggest something else?

**Comment by filmaj** [comment]
I would add a Requirements section, something like:

## Requirements

- node.js v6.3.1  or newer
- [`yarn`](https://yarnpkg.com/en/docs/install)

**Comment by slaanesh** [comment]
no worries for me for sure, feel free to submit a PR for it :)
