### ISSUE TITLE
Consider re-organizing documentation

### ISSUE THREAD

**Issue by filmaj** [adobe/stock-api-libjs#3]
Hi!

Just wanted to say thank you for the extensive documentation you provide in the README.

My one concern is that it makes the README very long. What does the Stock team think of splitting up usage documentation into its own document?

Also, I noticed your source code is impressively documented at the function level, JSDoc style, I _think_. That is rad! Maybe we could generate API reference docs based on your extensive function JS docs?

**Comment by slaanesh** [comment]
I don't see any issues with this. Would we be able to provide a PR for it?

**Comment by filmaj** [comment]
I will send a PR splitting out the usage documentation into its own file. I'm also tweaking the formatting and fixing up grammar where I can. I will send a PR for that along with a few questions / suggestions.

Another thought I had, reviewing and reading through the usage docs and the source code, is that we could possibly merge the extensive function descriptions in the usage documentation from the README straight into the function documentation signatures present in the source. We could try coupling that with an API reference generator (that would generate an API reference by analyzing the source code and pulling out function signatures/docs, perhaps during CD #4) and annotating it with the excellent example source code currently existing in the usage docs.

**Comment by filmaj** [comment]
@chfabbro that makes sense. I've opened up a PR in #5 around this issue with plenty of changes in there. I wonder if I could get your feedback on that when you have time? Probably makes sense to add a link to the docs as per your suggestion in there, if you approve of the general theme of changes.

**Comment by chfabbro** [comment]
**@filmaj** yes, I will. And thank you for your help!! The dev team has been reassigned and so I am currently the only person available to maintain these repos.

**Comment by filmaj** [comment]
No rush, at your leisure, and thanks for letting me know.

With regards to changing dev team, perhaps we should update the makeup of the Adobe-Stock team we have on github.com/adobe to reflect the proper ownership for this project?
